name: Scrape and Deploy
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm run scrape
      - run: npm run build
      - run: ls -la _site  # Debug: Verify _site contents
      - name: Deploy to Netlify
        run: npx netlify-cli deploy --prod --dir=_site
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
