name: Scrape and Deploy
on:
  push:
  schedule:
    - cron: '0 */6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: npm install
      - run: npm run scrape
      - run: ls -la posts  # Verify .md files
      - run: npm run build
      - run: ls -la _site  # Verify _site contents
      - run: cat _site/index.html  # Show index.html
      - name: Commit and Push Changes
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add .
          git commit -m "Add new outage posts" || echo "No changes to commit"
          git pull origin main --rebase
          git push origin main
      - name: Deploy to Netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: |
          echo "Deploying _site contents:"
          ls -la _site  # Confirm before deploy
          npx netlify-cli deploy --prod --dir=_site --site "$NETLIFY_SITE_ID"
