name: Scrape and Deploy
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: npm install
      - run: npm run scrape
      - run: ls -la posts
      - run: npm run build
      - run: ls -la _site
      - run: ls -la _site/posts
      - run: cat _site/index.html
      - name: Commit and Push Changes
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add .
          git commit -m "Add new outage posts" || echo "No changes to commit"
          git fetch origin main
          git reset --hard origin/main
          git add .
          git commit -m "Update with latest outage posts" || echo "No new changes"
          git push origin main
      - name: Deploy to Netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: |
          echo "Deploying _site contents:"
          ls -la _site
          npx netlify-cli deploy --prod --dir=_site --site "$NETLIFY_SITE_ID" --message "Deploy with latest outages"
