name: Scrape and Deploy
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history to avoid shallow clone issues
      - run: npm install
      - run: npm run scrape
      - run: npm run build
      - run: ls -la _site  # Debug: Verify _site contents
      - name: Commit and Push Changes
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git pull origin main --rebase  # Pull and rebase to integrate remote changes
          git add .
          git commit -m "Add new outage posts" || echo "No changes to commit"
          git push origin main
      - name: Deploy to Netlify
        run: npx netlify-cli deploy --prod --dir=_site
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
