name: Scrape and Deploy
on:
  workflow_dispatch: # Manual trigger only

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Dependencies
        run: npm install
      - name: Scrape Outage.Report
        run: npm run scrape
      - name: List Generated Posts
        run: ls -la posts
      - name: Show Post Contents
        run: cat posts/*.md || echo "No posts generated"
      - name: Clear Old Build
        run: rm -rf _site
      - name: Build Site with Eleventy
        run: npm run build
      - name: List Built Site
        run: ls -la _site
      - name: List Built Posts
        run: ls -la _site/posts
      - name: Show Index Page
        run: cat _site/index.html
      - name: Commit and Push Changes
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add .
          git commit -m "Add new outage posts" || echo "No changes to commit"
          git fetch origin main
          git reset --hard origin/main  # Sync with remote
          git add .
          git commit -m "Update with latest outage posts" || echo "No new changes"
          git push origin main --force  # Force push to ensure latest state
      - name: Deploy to Netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: |
          echo "Deploying _site contents:"
          ls -la _site
          npx netlify-cli deploy --prod --dir=_site --site "$NETLIFY_SITE_ID" --message "Deploy with latest Outage.Report data"
